---
title: "gono_sis"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(tidybayes)
library(bayesplot)
```


## Data Load

```{r}
data_cases <- read.csv('data/gono_q.csv')
data_denom <- read.csv('data/pop_denom.csv')
```


## Data Clean

```{r}
data_cases_f <- data_cases |>
  mutate(YearQ = yq(Year), 
         Year = year(YearQ)) |>
  filter(Sex == 'BOTH', Age == 'ALL', Year > 2020) |>
  rename(Cases = Case.Counts, Disease = Disease.Name)

data_denom_f <- data_denom |>
  filter(Age == 'ALL', Sex == 'BOTH') |>
  mutate(Year = as.integer(Year)) |>
  select(-Age, -Sex)

data_joined <- left_join(data_cases_f, data_denom_f, by = c('Year', 'Geography'))
data_joined <- data_joined |> 
  mutate(rate100k = round(1e5 * (Cases / Population), 2))
```

## Data exploration

```{r}
ggplot(data_joined) +
  geom_line(aes(y = Cases, x = YearQ)) +
  geom_point(aes(y = Cases, x = YearQ)) +
  theme_bw()
```


## Model prep

We are assuming we know nothing about the true S and I groupings.

```{r}
cases <- data_joined$Cases
pop_sus <- data_joined$Population - cases
ntime <- length(cases)

data_sis <- list(ntime = ntime, 
                 new_cases = cases,
                 pop_sus = c(pop_sus[1], pop_sus), # Extend out for Suscep
                 ts =  1:ntime, 
                 compute_loglik = TRUE)
```

## Model Simple

### Fit
```{r}
# SIMPLE MODEL
sis_model <- stan_model('sis_gono_simple.stan')
gono_model <- sampling(sis_model, data = data_sis,
                       seed = 1294,
                       cores = 4, chains = 4, iter = 3000,
                       control = list(adapt_delta = 0.995, max_treedepth = 14))

gono_model |> spread_draws(y[ntime, state])|> summarise_draws()
#tmp$y[,,2] |> colMeans() |> ggplot2() + geom_line()

```


### Plots

```{r}
gono_model |> 
  spread_draws(y[ntime, state])|> 
  median_qi() |>
  ggplot(aes(y = y, x = ntime)) +
  geom_pointinterval(aes(linewidth = -.width, ymin = .lower, ymax = .upper)) +
  facet_wrap(~state, scales = 'free_y')

mcmc_areas(gono_model, pars = c('beta', 'gamma'), point_est = 'median') + theme_bw()
#rstan::stan_plot(gono_model, pars = c('beta', 'gamma'))
```


```{r}
model_states_draws <- gono_model |> spread_draws(y[ntime, state])

# FITS
model_states_draws |>
  median_qi() |>
  mutate(state = factor(state, labels = c('S', 'I'))) |>
  ggplot() +
  geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntime, y = y), alpha = 0.25) +
  geom_line(aes(col = state, y = y, x = ntime)) +
  facet_wrap(~state, scales = 'free_y') +
  theme_bw()

model_states_draws |>
  median_qi() |>
  mutate(state = factor(state, labels = c('S', 'I'))) |>
  filter(state == 'I') |>
    ggplot() +
    geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntime, y = y), alpha = 0.25) +
    geom_line(aes(col = state, y = y, x = ntime)) + 
    geom_line(data = data_joined |> mutate(YearQ = 1:length(YearQ)), aes(y = Cases, x = YearQ)) +
    theme_bw()

# PREDS
gono_model |> 
    spread_draws(y_pred_s[ntimes], y_pred_i[ntimes]) |> 
    pivot_longer(cols = c('y_pred_s', 'y_pred_i'), names_to = 'state', values_to = 'count') |>
  group_by(ntimes, state) |>
  median_qi() |>
  ggplot() +
  geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntimes, y = count), alpha = 0.25) +
  geom_line(aes(col = state, y = count, x = ntimes)) +
  facet_wrap(~state, scales = 'free_y') +
  theme_bw()

# With actual
gono_model |> 
    spread_draws(y_pred_s[ntimes], y_pred_i[ntimes]) |> 
    pivot_longer(cols = c('y_pred_s', 'y_pred_i'), names_to = 'state', values_to = 'count') |>
  filter(state == 'y_pred_i') |>
  group_by(ntimes, state) |>
  median_qi() |>
  ggplot() +
  geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntimes, y = count), alpha = 0.25) +
  geom_line(aes(col = state, y = count, x = ntimes)) +
  geom_line(data = data_joined |> mutate(YearQ = 1:length(YearQ)), aes(y = Cases, x = YearQ)) +
  theme_bw()

# Reduce(cbind, rstan::extract(gono_model)[c('y_pred_s', 'y_pred_i')])
```


## Model ME

### Fit
```{r}
# MODEL WITH ME
sis_model_me <- stan_model('sis_gono_wME.stan')
gono_model_me <- sampling(sis_model_me, data = data_sis,
                       seed = 1294,
                       cores = 4, chains = 4, iter = 3000,
                       control = list(adapt_delta = 0.999, max_treedepth = 17))
```

### Plots

```{r}
gono_model_me |> 
    spread_draws(y_pred_s[ntimes], y_pred_i[ntimes]) |> 
    pivot_longer(cols = c('y_pred_s', 'y_pred_i'), names_to = 'state', values_to = 'count') |>
  filter(state == 'y_pred_i') |>
  group_by(ntimes, state) |>
  median_qi() |>
  ggplot() +
  geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntimes, y = count), alpha = 0.25) +
  geom_line(aes(col = state, y = count, x = ntimes)) +
  geom_line(data = data_joined |> mutate(YearQ = 1:length(YearQ)), aes(y = Cases, x = YearQ)) +
  theme_bw()
```

## Model ME + Contact Rates

### Fit

```{r}
sis_model_me_contact <- stan_model('sis_gono_me_contact.stan')

gono_model_me_contact <- sampling(sis_model_me_contact, data = data_sis,
                                  seed = 1294,
                                  cores = 4, chains = 4, iter = 3000,
                                  control = list(adapt_delta = 0.999, max_treedepth = 17))
```

### Plots

```{r}
gono_model_me_contact |> 
    spread_draws(y_pred_s[ntimes], y_pred_i[ntimes]) |> 
    pivot_longer(cols = c('y_pred_s', 'y_pred_i'), names_to = 'state', values_to = 'count') |>
  filter(state == 'y_pred_i') |>
  group_by(ntimes, state) |>
  median_qi() |>
  ggplot() +
  geom_ribbon(aes(fill = state, ymin = .lower, ymax = .upper, x = ntimes, y = count), alpha = 0.25) +
  geom_line(aes(col = state, y = count, x = ntimes)) +
  geom_line(data = data_joined |> mutate(YearQ = 1:length(YearQ)), aes(y = Cases, x = YearQ)) +
  theme_bw()
```

##

```{r}
sis_model_me_contact <- stan_model('sis_gono_me_contact.stan')

data_sis <- append(data_sis,
                   list(prodM = matrix(c(0.75, 0.25, 0.25, 0.75), nrow = 2)))

gono_model_me_contact <- sampling(sis_model_me_contact, data = data_sis,
                                  seed = 1294,
                                  cores = 4, chains = 4, iter = 3000,
                                  control = list(adapt_delta = 0.999, max_treedepth = 17))
```

